spring:
  profiles:
    active: prod
  datasource:
    data: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dbgirl
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

